# render.yaml

services:
  - type: web
    name: guard-io
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python api/index.py" # Pointing to the main entry script
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
    healthCheckPath: "/"
